using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace TEGFI_3
{
    public static class FileAccesser
    {
        public static void WriteNewFile() // Writes a header to the file
        {
            // this will return a current project path, probably in bin / debug folder
            string destPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, ("REPORT.txt"));
            using (StreamWriter file =
             new StreamWriter(destPath, true))
            {
                file.WriteLine("\t\t\tThis report has been generated by TEGFI App\n");
                file.WriteLine("Today's date is: \t" + DateTime.Now);
                file.WriteLine("\n");
            }
            //Console.WriteLine("These expenses were saved to a log file");
        }

        public static void WriteASingleValue(object value) // Writes an individual values
        {
            // this will return a current project path, probably in bin / debug folder
            string destPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, ("REPORT.txt"));
            using (StreamWriter file =
             new StreamWriter(destPath, true))
            {
                file.Write(value);
            }
            //Console.WriteLine("These expenses were saved to a log file");
        }
        public static void NewLine() // Writes an individual values
        {
            // this will return a current project path, probably in bin / debug folder
            string destPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, ("REPORT.txt"));
            using (StreamWriter file =
             new StreamWriter(destPath, true))
            {
                file.WriteLine();
            }
            //Console.WriteLine("These expenses were saved to a log file");
        }

    }
}
